name: Deployment With Re-Usable
on:
  workflow_call:
    inputs:
      files-name:
        required: true
        default: dist
        type: string
        description: A Reusable Workflows Inputs name
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.files-name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
